module.exports = {

    //GENERAL
    INTERNAL_ERROR_MESSAGE: "INTERNAL_ERROR",
    NOT_FOUND_ERROR_MESSAGE: "NOT_FOUND",
    SUCCEEDED_MESSAGE: "SUCCEEDED",
    FAILED_MESSAGE:"FAILED_MESSAGE",
    TOKEN_SECRET: "1F0wpSxLsrl2rk]oXzTp223=iJC4}y+YR+l*396VG39p8HtC36",
    //VALIDATION
    INVALID_PARAMETER_SENDED:'FAILED',
  };
